# 데이터 담기

- 리스트 자료형

- 딕셔너리 자료형

In [16]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'AAA':[4,5,6,7], 'BBB':[10, 20, 30, 40], 'CCC':[100, 50, -30, -50]})
df

ModuleNotFoundError: No module named 'DataFrame'

In [11]:
df.loc[df['AAA']>=5, 'BBB']=-1
df

AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

In [13]:
df.loc[df.AAA >= 5, ['BBB','CCC']]=555
df

AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

In [14]:
df.loc[df.AAA < 5, ['BBB','CCC']]=2000
df

AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

In [20]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list['abcd'])
df1

TypeError: 'type' object is not subscriptable

In [21]:
df1 = pd.DataFrame(np.arange(12.0).reshape((3,4)), columns = list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [22]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [24]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [26]:
df1.reindex(columns=df2.columns, fill_value=0)
# df2컬럼 값을 재 정렬. df1에 없던 e가 생성, NaN인 공간에 0으로 채움

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [27]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
arr[0]

array([0., 1., 2., 3.])

In [29]:
arr - arr[0]
# 행끼리 차 구하기

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [34]:
frame=pd.DataFrame(np.arange(12.0).reshape((4,3)), columns = list('bde'),
               index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [35]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [36]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [37]:
series1 = frame.loc['Utah']
series1

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [38]:
frame - series1

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [40]:
from pandas import Series
series2 = Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [41]:
frame+series2
# 둘 중 하나라도 없으면 NaN

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [42]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [43]:
frame.sub(series3, axis=0)
# axis=0이니까 열 기준으로 차를 구한다.

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [46]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                 index = ['Utah', 'Ohio', 'Texas','Oregon'])
frame

b         d         e
Utah    0.960452  0.051971  0.109223
Ohio    1.374564 -0.497121  1.087969
Texas   0.303195  1.802388 -0.436763
Oregon  0.886752 -0.313235 -1.469474

In [47]:
np.abs(frame)

b         d         e
Utah    0.960452  0.051971  0.109223
Ohio    1.374564  0.497121  1.087969
Texas   0.303195  1.802388  0.436763
Oregon  0.886752  0.313235  1.469474

In [48]:
f = lambda x: x.max() - x.min()

In [49]:
frame.apply(f)

b    1.071369
d    2.299510
e    2.557443
dtype: float64

In [50]:
frame.apply(f, axis=1)

Utah      0.908480
Ohio      1.871685
Texas     2.239152
Oregon    2.356226
dtype: float64

In [51]:
# lambda 표현식
# lambda x, y: x+y
# lambda x, y: x*y

In [52]:
xs = list(range(19))
xs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [53]:
doubled = map(lambda x: x*2,xs)
doubled

In [54]:
squared = map(lambda x: (x+1) **2, xs)
list(squared)

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [55]:
for x in doubled:
    print(x)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36


In [57]:
doubled = [x*2 for x in xs]
squared = [(x+1)**2 for x in xs]

In [58]:
xs = list(range(10))
xs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
doubled = map(lambda x: x*2, xs)
doubled

In [62]:
squared=map(lambda x: (x+1) **2, xs)
list(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [63]:
evens = filter(lambda x:x%2 is 0, xs)
list(evens)

[0, 2, 4, 6, 8]

In [65]:
li = [-3, -2, 0, 6, 8]
max_xs = li.max()
max_xs

AttributeError: 'list' object has no attribute 'max'

In [66]:

from functools import reduce 
li = [-3, -2, 0, 6, 8]

In [67]:
li

[-3, -2, 0, 6, 8]

In [69]:
max_xs=max(li)
max_xs

8

In [79]:
# li의 최대값을 구하여 max_xs에 저장하여라.
max_xs = reduce(lambda x,y: x if x>y else y, li)
max_xs

8

In [76]:
# li의 숫자들이 음수면 음수, 0이면 0, 양수면 양수를 출력하여라.
list(map(lambda i : '양수' if i > 0 else('음수' if i<0 else 0), li))

['음수', '음수', 0, '양수', '양수']

In [77]:
# map()을 이용하여 리스트 a와 리스트 b의 합을 구하여 출력하라.
a = [1,2,3,4]
b = [5,6,7,8]
list(map(lambda x, y: x+y, a, b ))

[6, 8, 10, 12]

In [80]:
def f(x):
    return Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)

b         d         e
min  0.303195 -0.497121 -1.469474
max  1.374564  1.802388  1.087969

In [81]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d      e
Utah    0.96   0.05   0.11
Ohio    1.37  -0.50   1.09
Texas   0.30   1.80  -0.44
Oregon  0.89  -0.31  -1.47

In [82]:
frame['e'].map(format)

Utah       0.11
Ohio       1.09
Texas     -0.44
Oregon    -1.47
Name: e, dtype: object

In [84]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [87]:
frame = pd.DataFrame(np.arange(8).reshape(2,4), 
                     index=['three', 'one'], 
                     columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [86]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [92]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()
# 값이 아닌 순위 값이 나타난다

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [89]:
obj.rank(method = 'first')


0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [90]:
obj.rank(method = 'min')

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [91]:
obj.rank(method = 'max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [96]:
import numpy as np
from numpy import nan


In [99]:
df= pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                 [np.nan, np.nan], [0.75, -1.3]],
               index = ['a', 'b', 'c', 'd'],
               columns = ['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [100]:
df.idxmin()

one    d
two    b
dtype: object

In [101]:
df.idxmax()

one    b
two    d
dtype: object

In [102]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [103]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [104]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [106]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [108]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [109]:
obj.value_counts(normalize = True)

a    0.333333
c    0.333333
b    0.222222
d    0.111111
dtype: float64